In [24]:
import numpy as np 

# training data : 

| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |   
| ----------------| ------------------- |----------------- |--------------|-------------- |  
| 2104            | 5                   | 1                | 45           | 460           |  
| 1416            | 3                   | 2                | 40           | 232           |  
| 852             | 2                   | 1                | 35           | 178           |  



In [25]:
# Training data: each row represents one house
# Features (columns):
# [0] Size in square feet
# [1] Number of bedrooms
# [2] Number of floors
# [3] Age of home in years
x_train = np.array([[2104, 5, 1, 45],
                    [1416, 3, 2, 40],
                    [852, 2, 1, 35]])

# Target values: house prices in $1000's
y_train = np.array([460, 232, 178])

print(x_train)

# Print the shape of the input feature matrix (m examples, n features)
print(x_train.shape)

print(y_train)

# Print the shape of the output vector
print(y_train.shape)


[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
(3, 4)
[460 232 178]
(3,)


In [26]:
# Initialize model parameters 

# Initial bias term 
b_init = 785.1811367994083

# Initial weights for each feature:
# [0] Size in square feet
# [1] Number of bedrooms
# [2] Number of floors
# [3] Age of home in years
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

print(w_init.shape)


# Number of training examples (rows in x_train)
m = x_train.shape[0]


(4,)


# model prediction :
$$ f_{\mathbf{w},b}(\mathbf{x}) =  w_0x_0 + w_1x_1 +... + w_{n-1}x_{n-1} + b \tag{1}$$
or in vector notation:
$$ f_{\mathbf{w},b}(\mathbf{x}) = \mathbf{w} \cdot \mathbf{x} + b  \tag{2} $$ 


In [27]:
# Model prediction from scratch using linear regression

def linear_regression_function(w, x, b):
    """    
    Args:
        x (ndarray): Shape (n,) example with multiple features
        w (ndarray): Shape (n,) model weights (parameters)    
        b (scalar): Bias term (intercept)    

    Returns:
        final_f (scalar): Predicted price
    """
    n = x.shape[0]  # Number of features
    f = 0         
    for i in range(n):
        f += x[i] * w[i]  
    final_f = f + b       
    return final_f        


In [28]:
# Example: choose the first training sample with 4 features
x_sample = x_train[0, 0:4]  

# Call the prediction function with initial weights and bias
price = linear_regression_function(w_init, x_sample, b_init)

# Output the prediction in a readable format
print(f"The price for a house with {x_train[0][0]} sqft, {x_train[0][1]} bedrooms, "
      f"{x_train[0][2]} floors, and {x_train[0][3]} years old is: ${round(price)}")

The price for a house with 2104 sqft, 5 bedrooms, 1 floors, and 45 years old is: $460


In [29]:
# model prediction using np.dot() :
def linear_regression_function2(w,x,b):
    """
    Args:
      x (ndarray): Shape (n,) example with multiple features
      w (ndarray): Shape (n,) model parameters   
      b (scalar):             model parameter 
      
    Returns:
        (scalar):  price
    """
    return  np.dot(x, w) + b

In [30]:
# Example: choose the first training sample with 4 features
x_sample = x_train[0, 0:4]  

# Call the prediction function with initial weights and bias
price = linear_regression_function2(w_init, x_sample, b_init)

# Output the prediction in a readable format
print(f"The price for a house with {x_train[0][0]} sqft, {x_train[0][1]} bedrooms, "
      f"{x_train[0][2]} floors, and {x_train[0][3]} years old is: ${round(price)}")

The price for a house with 2104 sqft, 5 bedrooms, 1 floors, and 45 years old is: $460
