In [1]:
import numpy as np 

In [ ]:
# Training data: each row represents one house
# Features (columns):
# [0] Size in square feet
# [1] Number of bedrooms
# [2] Number of floors
# [3] Age of home in years
x_train = np.array([[2104, 5, 1, 45],
                    [1416, 3, 2, 40],
                    [852, 2, 1, 35]])

# Target values: house prices in $1000's
y_train = np.array([460, 232, 178])

print(x_train)

# Print the shape of the input feature matrix (m examples, n features)
print(x_train.shape)

print(y_train)

# Print the shape of the output vector
print(y_train.shape)


[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
(3, 4)
[460 232 178]
(3,)


In [5]:
# Initialize model parameters 

# Initial bias term 
b_init = 785.1811367994083

# Initial weights for each feature:
# [0] Size in square feet
# [1] Number of bedrooms
# [2] Number of floors
# [3] Age of home in years
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

print(w_init.shape)


# Number of training examples (rows in x_train)
m = x_train.shape[0]


(4,)
